### ISSUE TITLE
How to get the logged in userId

### ISSUE THREAD

**Issue by sferoze** [ongoworks/meteor-ddp-login#2]
Hello,
 I am using this package to connect a client only Meteor app to a preexisting meteor server. 

Once I login, how can I get the userId? 

Currently on startup I do

Meteor.disconnect()
conn = DDP.connect(remoteServerURL)

conn.subscribe and stuff works

but conn.userId() and conn.user() does not work. 

how can I get the userId() ? Do I just have to call a meteor function and have it return the userId for the logged in user?

**Comment by aaronjudd** [comment]
how about adding a method on the remote server that returns Meteor.userId() and then using conn.call("getUserIdMethod")?

**Comment by aldeed** [comment]
As long as the login method is returning an object with `id` property, the userId should be set properly here: https://github.com/ongoworks/meteor-ddp-login/blob/master/ddp-login.js#L49

So `conn.userId()` should work, though it might not be reactive.

The core code this is taken from has changed a bit since this was written. We should probably update at some point. But I think it's still essentially the same flow.
